SELECT 
CASE
    WHEN F.CODE = '360.10.01.001' THEN 'ÜCRET GELİR VERGİSİ'
    WHEN F.CODE = '360.10.01.002' THEN 'S.M MAKBUZU'
    WHEN F.CODE = '360.10.01.003' THEN 'KİRA GELİR VERGİSİ'
    WHEN F.CODE = '360.10.01.004' THEN 'GİDER PUSULASI GELİR VERGİSİ'
    WHEN F.CODE = '360.10.01.005' THEN 'YURT DIŞI HİZMERT ALIMI GELİR VERGİSİ'
    WHEN F.CODE LIKE '7%' THEN 'VERGİ' 
END as odenecekGelirVergileri,
CASE
    WHEN F.CODE = '360.10.01.001' THEN 'ÜCRET GELİR VERGİSİ'
    WHEN F.CODE = '360.10.01.002' THEN '022'
    WHEN F.CODE = '360.10.01.003' THEN '041'
    WHEN F.CODE = '360.10.01.004' THEN '156'
    WHEN F.CODE = '360.10.01.005' THEN '279'
    WHEN F.CODE LIKE '7%' THEN ''
END as vergiTuru,
A.DATE_ as tarih,
MONTH(A.DATE_) as ay,
YEAR(A.DATE_) as yil,
AA.FICHENO as fisNo,
CASE 
    WHEN A.TRCODE=1 THEN '1 Açılış'
    WHEN A.TRCODE=2 THEN '2 Tahsil'
    WHEN A.TRCODE=3 THEN '3 Tediye'
    WHEN A.TRCODE=4 THEN '4 Mahsup'
    WHEN A.TRCODE=5 THEN '5 Özel'
    WHEN A.TRCODE=6 THEN '6 Kur Farkı'
    WHEN A.TRCODE=7 THEN '7 Kapanış'
    ELSE '' 
END as islem,
CAST(C.NR AS CHAR(3))+' '+C.NAME as isYeri,
CAST(D.NR AS CHAR(3))+' '+D.NAME as bolum,
E.CODE+' '+E.NAME as proje,
F1.CODE as kebirHesabiKodu,
F1.DEFINITION_ as kebirHesabiAdi,
F.CODE as hesapKodu,
F.DEFINITION_ as hesapAdi,
G.CODE+' '+G.DEFINITION_ as masrafMerkezi,
CASE 
    WHEN AA.MODULENR=1 THEN '1 Malzeme'
    WHEN AA.MODULENR=2 THEN '2 Satınalma'
    WHEN AA.MODULENR=3 THEN '3 Satış'
    WHEN AA.MODULENR=4 THEN '4 Cari Hesap'
    WHEN AA.MODULENR=5 THEN '5 Çek Senet'
    WHEN AA.MODULENR=6 THEN '6 Banka'
    WHEN AA.MODULENR=7 THEN '7 Kasa'
    ELSE '' 
END as kaynakModul,
-CASE 
    WHEN A.TRCURR=0 AND (A.LOGICALREF NOT IN (SELECT DISTINCT PREVLINEREF FROM LG_600_01_ACCDISTDETLN) OR A1.DISTRATE=1) THEN ABS(A.DEBIT-A.CREDIT)-ABS(A.DEBIT-A.CREDIT)*2*A.SIGN
    WHEN A.TRCURR<>0 AND (A.LOGICALREF NOT IN (SELECT DISTINCT PREVLINEREF FROM LG_600_01_ACCDISTDETLN) OR A1.DISTRATE=1) THEN A.TRNET-A.TRNET*2*A.SIGN
    WHEN A.TRCURR=0 AND A1.DISTRATE<>100 THEN A1.CREDEBNET-A1.CREDEBNET*2*A.SIGN
    WHEN A.TRCURR<>0 AND A1.DISTRATE<>100 THEN A1.TRNET-A1.TRNET*2*A.SIGN
    ELSE 0 
END  as tutar,
CASE 
    WHEN A.LOGICALREF NOT IN (SELECT DISTINCT PREVLINEREF FROM LG_600_01_ACCDISTDETLN) OR A1.DISTRATE=1 THEN ABS(A.DEBIT-A.CREDIT)-ABS(A.DEBIT-A.CREDIT)*2*A.SIGN 
    ELSE A1.CREDEBNET-A1.CREDEBNET*2*A.SIGN 
END as tutarYerel,
A.LINEEXP as aciklama,
AA.GENEXP1 as fisAciklama,
CASE 
    WHEN A.SIGN=0 THEN '0 Borç' WHEN A.SIGN=1 THEN '1 Alacak' 
    ELSE '' 
END as hareketYonu,
CASE 
    WHEN A.CANCELLED=0 THEN 'Hayır' 
    ELSE 'Evet' 
END as iptal,
CASE AA.DOCTYPE 
    WHEN 0 THEN 'Normal' 
    WHEN 1 THEN 'Cost Of Sales' 
    WHEN 2 THEN 'Differences Of Cost Of Sales' 
    ELSE '' 
END as belgeTuru,
A.CLDEF as cari,
A.TAXNR as cariVergiNo,
CL.DEFINITION_ as cariUnvan1, 
CL.DEFINITION2 as cariUnvan2,
CL.NAME as adi, 
CL.SURNAME as soyadi,
N2.DOCODE as faturaBelgeNo, 
N2.FICHENO as faturaNo,
CL.ADDR1 as adres1,
CL.COUNTRY as ulke,
-1 * SEML.TOTAL as vergi
FROM  LG_600_01_EMFLINE A WITH(NOLOCK)
    LEFT JOIN LG_600_01_EMFICHE AA WITH(NOLOCK) ON AA.LOGICALREF=A.ACCFICHEREF
    LEFT JOIN LG_600_01_ACCDISTDETLN A1 WITH(NOLOCK) ON A1.PREVLINEREF=A.LOGICALREF
    LEFT JOIN L_CAPIDIV C WITH(NOLOCK) ON C.NR=A.BRANCH AND C.FIRMNR=600
    LEFT JOIN L_CAPIDEPT D WITH(NOLOCK) ON D.NR=A.DEPARTMENT AND D.FIRMNR=600
    LEFT JOIN LG_600_PROJECT E WITH(NOLOCK) ON E.LOGICALREF=A1.PROJECTREF
    LEFT JOIN LG_600_EMUHACC F WITH(NOLOCK) ON F.LOGICALREF=A.ACCOUNTREF
    LEFT JOIN LG_600_EMUHACC F1 WITH(NOLOCK) ON F1.CODE=left(F.CODE,3)
    LEFT JOIN LG_600_EMCENTER G WITH(NOLOCK) ON G.LOGICALREF=A.CENTERREF
    LEFT JOIN L_CURRENCYLIST H WITH(NOLOCK) ON H.CURTYPE=A.TRCURR AND H.FIRMNR=600
    LEFT JOIN LG_EXCHANGE_600 I WITH(NOLOCK) ON I.EDATE=A.DATE_ AND I.CRTYPE=20
    LEFT JOIN LG_600_01_INVOICE N1 WITH(NOLOCK) ON N1.LOGICALREF = A.SOURCEFREF
    LEFT JOIN LG_600_01_INVOICE N2 WITH(NOLOCK) ON N2.ACCFICHEREF = AA.LOGICALREF
    LEFT JOIN LG_600_CLCARD CL WITH(NOLOCK)  ON CL.LOGICALREF = N2.CLIENTREF
    INNER JOIN (
                SELECT
                EML.ACCFICHEREF, 
                CASE 
                    WHEN EML.LOGICALREF NOT IN (SELECT DISTINCT PREVLINEREF FROM LG_600_01_ACCDISTDETLN) OR A1.DISTRATE=1 THEN ABS(EML.DEBIT-EML.CREDIT)-ABS(EML.DEBIT-EML.CREDIT)*2*EML.SIGN 
                    ELSE A1.CREDEBNET-A1.CREDEBNET*2*EML.SIGN 
                END AS TOTAL
                FROM  LG_600_01_EMFLINE EML WITH(NOLOCK)
                    LEFT JOIN LG_600_01_EMFICHE AA WITH(NOLOCK) ON AA.LOGICALREF=EML.ACCFICHEREF
                    LEFT JOIN LG_600_01_ACCDISTDETLN A1 WITH(NOLOCK) ON A1.PREVLINEREF=EML.LOGICALREF
                    LEFT JOIN LG_600_EMUHACC F WITH(NOLOCK) ON F.LOGICALREF=EML.ACCOUNTREF
                WHERE AA.CANCELLED = 0
                    AND (F.CODE LIKE '360.10.01%')
                    AND MONTH(EML.DATE_)=4                                               --PARAMETER MONTH
                    AND YEAR(EML.DATE_)=2025                             --PARAMETER YEAR
                    and AA.MODULENR=2
                ) SEML ON  SEML.ACCFICHEREF = A.ACCFICHEREF
WHERE AA.CANCELLED = 0
    AND (F.CODE LIKE '7%')
    AND MONTH(A.DATE_)=4                      --PARAMETER MONTH
    AND YEAR(A.DATE_)=2025                   --PARAMETER YEAR
    and AA.MODULENR=2
UNION ALL
SELECT 
CASE
    WHEN F.CODE = '360.10.01.001' THEN 'ÜCRET GELİR VERGİSİ'
    WHEN F.CODE = '360.10.01.002' THEN 'S.M MAKBUZU'
    WHEN F.CODE = '360.10.01.003' THEN 'KİRA GELİR VERGİSİ'
    WHEN F.CODE = '360.10.01.004' THEN 'GİDER PUSULASI GELİR VERGİSİ'
    WHEN F.CODE = '360.10.01.005' THEN 'YURT DIŞI HİZMERT ALIMI GELİR VERGİSİ'
    WHEN F.CODE LIKE '7%' THEN 'VERGİ'
END as odenecekGelirVergileri,
CASE
    WHEN F.CODE = '360.10.01.001' THEN 'ÜCRET GELİR VERGİSİ'
    WHEN F.CODE = '360.10.01.002' THEN '022'
    WHEN F.CODE = '360.10.01.003' THEN '041'
    WHEN F.CODE = '360.10.01.004' THEN '156'
    WHEN F.CODE = '360.10.01.005' THEN '279'
    WHEN F.CODE LIKE '7%' THEN ''
END as vergiTuru,
A.DATE_ as tarih,
MONTH(A.DATE_) as ay,
YEAR(A.DATE_) as yil,
AA.FICHENO as fisNo,
CASE 
    WHEN A.TRCODE=1 THEN '1 Açılış'
    WHEN A.TRCODE=2 THEN '2 Tahsil'
    WHEN A.TRCODE=3 THEN '3 Tediye'
    WHEN A.TRCODE=4 THEN '4 Mahsup'
    WHEN A.TRCODE=5 THEN '5 Özel'
    WHEN A.TRCODE=6 THEN '6 Kur Farkı'
    WHEN A.TRCODE=7 THEN '7 Kapanış'
    ELSE '' 
END as islem,
CAST(C.NR AS CHAR(3))+' '+C.NAME as isYeri,
CAST(D.NR AS CHAR(3))+' '+D.NAME as bolum,
E.CODE+' '+E.NAME as proje,
F1.CODE as kebirHesabiKodu,
F1.DEFINITION_ as kebirHesabiAdi,
F.CODE as hesapKodu,
F.DEFINITION_ as hesapAdi,
G.CODE+' '+G.DEFINITION_ as masrafMerkezi,
CASE 
WHEN AA.MODULENR=1 THEN '1 Malzeme'
    WHEN AA.MODULENR=2 THEN '2 Satınalma'
    WHEN AA.MODULENR=3 THEN '3 Satış'
    WHEN AA.MODULENR=4 THEN '4 Cari Hesap'
    WHEN AA.MODULENR=5 THEN '5 Çek Senet'
    WHEN AA.MODULENR=6 THEN '6 Banka'
    WHEN AA.MODULENR=7 THEN '7 Kasa'
    ELSE '' 
END as kaynakModul,
-CASE 
    WHEN A.TRCURR=0 AND (A.LOGICALREF NOT IN (SELECT DISTINCT PREVLINEREF FROM LG_600_01_ACCDISTDETLN) OR A1.DISTRATE=1) THEN ABS(A.DEBIT-A.CREDIT)-ABS(A.DEBIT-A.CREDIT)*2*A.SIGN
    WHEN A.TRCURR<>0 AND (A.LOGICALREF NOT IN (SELECT DISTINCT PREVLINEREF FROM LG_600_01_ACCDISTDETLN) OR A1.DISTRATE=1) THEN A.TRNET-A.TRNET*2*A.SIGN
    WHEN A.TRCURR=0 AND A1.DISTRATE<>100 THEN A1.CREDEBNET-A1.CREDEBNET*2*A.SIGN
    WHEN A.TRCURR<>0 AND A1.DISTRATE<>100 THEN A1.TRNET-A1.TRNET*2*A.SIGN
    ELSE 0 
END as tutar,
CASE 
    WHEN A.LOGICALREF NOT IN (SELECT DISTINCT PREVLINEREF FROM LG_600_01_ACCDISTDETLN) OR A1.DISTRATE=1 THEN ABS(A.DEBIT-A.CREDIT)-ABS(A.DEBIT-A.CREDIT)*2*A.SIGN 
    ELSE A1.CREDEBNET-A1.CREDEBNET*2*A.SIGN 
END as tutarYerel,
A.LINEEXP as aciklama,
AA.GENEXP1 as fisAciklama,
CASE 
    WHEN A.SIGN=0 THEN '0 Borç' 
    WHEN A.SIGN=1 THEN '1 Alacak' 
    ELSE '' 
END as hareketYonu,
CASE 
    WHEN A.CANCELLED=0 THEN 'Hayır' 
    ELSE 'Evet' 
END  as iptal,
CASE AA.DOCTYPE 
    WHEN 0 THEN 'Normal' 
    WHEN 1 THEN 'Cost Of Sales' 
    WHEN 2 THEN 'Differences Of Cost Of Sales' 
    ELSE '' 
END as belgeTuru,
A.CLDEF as cari, 
A.TAXNR as cariVergiNo,
CL.DEFINITION_ as cariUnvan1, 
CL.DEFINITION2 as cariUnvan2,
CL.NAME as adi, 
CL.SURNAME as soyadi,
N2.DOCODE as faturaBelgeNo, 
N2.FICHENO as faturaNo,
CL.ADDR1 as adres1,
CL.COUNTRY as ulke,
-1 * SEML.TOTAL as vergi
FROM  LG_600_01_EMFLINE A WITH(NOLOCK)
    LEFT JOIN LG_600_01_EMFICHE AA WITH(NOLOCK) ON AA.LOGICALREF=A.ACCFICHEREF
    LEFT JOIN LG_600_01_ACCDISTDETLN A1 WITH(NOLOCK) ON A1.PREVLINEREF=A.LOGICALREF
    LEFT JOIN L_CAPIDIV C WITH(NOLOCK) ON C.NR=A.BRANCH AND C.FIRMNR=600
    LEFT JOIN L_CAPIDEPT D WITH(NOLOCK) ON D.NR=A.DEPARTMENT AND D.FIRMNR=600
    LEFT JOIN LG_600_PROJECT E WITH(NOLOCK) ON E.LOGICALREF=A1.PROJECTREF
    LEFT JOIN LG_600_EMUHACC F WITH(NOLOCK) ON F.LOGICALREF=A.ACCOUNTREF
    LEFT JOIN LG_600_EMUHACC F1 WITH(NOLOCK) ON F1.CODE=left(F.CODE,3)
    LEFT JOIN LG_600_EMCENTER G WITH(NOLOCK) ON G.LOGICALREF=A.CENTERREF
    LEFT JOIN L_CURRENCYLIST H WITH(NOLOCK) ON H.CURTYPE=A.TRCURR AND H.FIRMNR=600
    LEFT JOIN LG_EXCHANGE_600 I WITH(NOLOCK) ON I.EDATE=A.DATE_ AND I.CRTYPE=20
    LEFT JOIN LG_600_01_INVOICE N1 WITH(NOLOCK) ON N1.LOGICALREF = A.SOURCEFREF
    LEFT JOIN LG_600_01_INVOICE N2 WITH(NOLOCK) ON N2.ACCFICHEREF = AA.LOGICALREF
    INNER JOIN LG_600_CLCARD CL WITH(NOLOCK)  ON CL.LOGICALREF = N2.CLIENTREF
    INNER JOIN (
                SELECT
                EML.ACCFICHEREF, 
                CASE
                    WHEN EML.LOGICALREF NOT IN (SELECT DISTINCT PREVLINEREF FROM LG_600_01_ACCDISTDETLN) OR A1.DISTRATE=1 THEN ABS(EML.DEBIT-EML.CREDIT)-ABS(EML.DEBIT-EML.CREDIT)*2*EML.SIGN 
                    ELSE A1.CREDEBNET-A1.CREDEBNET*2*EML.SIGN 
                END AS TOTAL
                FROM  LG_600_01_EMFLINE EML WITH(NOLOCK)
                    LEFT JOIN LG_600_01_EMFICHE AA WITH(NOLOCK) ON AA.LOGICALREF=EML.ACCFICHEREF
                    LEFT JOIN LG_600_01_ACCDISTDETLN A1 WITH(NOLOCK) ON A1.PREVLINEREF=EML.LOGICALREF
                    LEFT JOIN LG_600_EMUHACC F WITH(NOLOCK) ON F.LOGICALREF=EML.ACCOUNTREF
                WHERE AA.CANCELLED = 0
                    AND (F.CODE LIKE '360.10.01%')
                    AND MONTH(EML.DATE_)=4                               --PARAMETER MONTH
                    AND YEAR(EML.DATE_)=2025             --PARAMETER YEAR
                    AND AA.MODULENR=6
                ) SEML ON  SEML.ACCFICHEREF = A.ACCFICHEREF
WHERE AA.CANCELLED = 0
    AND (F.CODE LIKE '740.YÜ[PM]%' OR F.CODE LIKE '770.10.08.001')
    AND MONTH(A.DATE_)=4                      --PARAMETER MONTH
    AND YEAR(A.DATE_)=2025                   --PARAMETER YEAR
    AND AA.MODULENR=6
 